# Generated by Django 4.0.5 on 2022-08-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_individuals_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Individuals_info',
        ),
    ]
