# Generated by Django 4.0.5 on 2022-08-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_delete_individuals_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='individual_info',
            table='info',
        ),
    ]
