# Generated by Django 4.0.5 on 2022-08-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_individual_info_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='individual_info',
            table=None,
        ),
    ]
