# Generated by Django 4.0.5 on 2022-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='careerInterest',
            field=models.CharField(default=1, max_length=100, verbose_name='관심분야'),
            preserve_default=False,
        ),
    ]
