# Generated by Django 4.0.5 on 2022-08-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='referring_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='referring_user',
        ),
        migrations.RenameField(
            model_name='individual_info',
            old_name='user',
            new_name='referring_user',
        ),
        migrations.RenameField(
            model_name='informations',
            old_name='user',
            new_name='referring_user',
        ),
    ]
