# Generated by Django 4.0.5 on 2022-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_blog_referring_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='referring_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='referring_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='individual_info',
            old_name='referring_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='informations',
            old_name='referring_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
